import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Sidebar dùng chung cho 2 mục Luyện nói (speaking/) và Luyện viết (writing/).
const sidebars: SidebarsConfig = {
  skillSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
