import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Sidebar dùng chung cho các mục Luyện nói (speaking/) và Luyện phản xạ (reflex/).
const sidebars: SidebarsConfig = {
  skillSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
